// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/servers": {
            "get": {
                "description": "Retrieve a list of all registered VPN servers with their status and capacity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Get all VPN servers",
                "responses": {
                    "200": {
                        "description": "List of all servers",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ServerResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new VPN server node with WireGuard agent connection details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Register a new VPN server",
                "parameters": [
                    {
                        "description": "Server registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateServerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Server created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "409": {
                        "description": "Server ID already exists",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/admin/servers/healthy": {
            "get": {
                "description": "Retrieve only servers that are active, healthy, and have available capacity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Get healthy VPN servers",
                "responses": {
                    "200": {
                        "description": "List of healthy servers",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ServerResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/admin/servers/{serverId}/status": {
            "put": {
                "description": "Update a VPN server's operational status and health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Servers"
                ],
                "summary": "Update server status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "serverId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateServerStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server status updated successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Retrieve a list of all registered VPN users with their WireGuard configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all VPN users",
                "responses": {
                    "200": {
                        "description": "List of all users",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/users/by-public-key": {
            "get": {
                "description": "Retrieve a specific user's information using their WireGuard public key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by WireGuard public key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "WireGuard public key (44 characters base64)",
                        "name": "publicKey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User found and returned with full details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request - missing publicKey query parameter",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - no user exists with given public key",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database operation failed",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Register a new VPN user with email and IP address. Automatically generates WireGuard public/private key pair and returns ready-to-use configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new VPN user",
                "parameters": [
                    {
                        "description": "User registration request with email and IP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully with WireGuard configuration",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input - invalid email format or IP address format",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - email or IP address already registered",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or WireGuard operation failed",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/users/toggle": {
            "post": {
                "description": "Connect or disconnect a VPN user by public key. Supports idempotent operations - calling with the same state returns success",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Toggle user VPN connection status",
                "parameters": [
                    {
                        "description": "Toggle request with public key and action (connect/disconnect)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ToggleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Connection toggled successfully with updated user state",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ToggleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input - invalid public key format or invalid action value",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Not found - user with given public key does not exist",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database or WireGuard operation failed",
                        "schema": {
                            "$ref": "#/definitions/response.JSONResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateServerRequest": {
            "type": "object",
            "required": [
                "agentApiKey",
                "agentUrl",
                "countryCode",
                "id",
                "location",
                "maxClients",
                "name",
                "networkCidr",
                "publicIp",
                "regionCode",
                "serverPublicKey",
                "wireguardPort"
            ],
            "properties": {
                "agentApiKey": {
                    "type": "string",
                    "example": "secret-key-nyc"
                },
                "agentUrl": {
                    "type": "string",
                    "example": "https://wg-agent-nyc.example.com"
                },
                "bandwidthLimitMbps": {
                    "type": "integer",
                    "example": 1000
                },
                "countryCode": {
                    "type": "string",
                    "example": "US"
                },
                "id": {
                    "type": "string",
                    "example": "us-newyork"
                },
                "latitude": {
                    "type": "number",
                    "example": 40.7128
                },
                "location": {
                    "type": "string",
                    "example": "New York, USA"
                },
                "longitude": {
                    "type": "number",
                    "example": -74.006
                },
                "maxClients": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 250
                },
                "name": {
                    "type": "string",
                    "example": "New York"
                },
                "networkCidr": {
                    "type": "string",
                    "example": "192.168.88.0/24"
                },
                "publicIp": {
                    "type": "string",
                    "example": "192.0.2.1"
                },
                "regionCode": {
                    "type": "string",
                    "example": "us-east"
                },
                "serverPublicKey": {
                    "type": "string",
                    "example": "ABC123..."
                },
                "wireguardPort": {
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 1,
                    "example": 51820
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "ip"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "ip": {
                    "type": "string",
                    "example": "10.0.0.2"
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2025-02-07T08:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "ip": {
                    "type": "string",
                    "example": "10.0.0.2"
                },
                "publicKey": {
                    "type": "string",
                    "example": "QGF4I+0L7klYTozF8pFDZUKC4fGt3tEuCakfWYghN0Y="
                },
                "userId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "wireGuardConfig": {
                    "type": "string"
                }
            }
        },
        "dto.ServerResponse": {
            "type": "object",
            "properties": {
                "agentUrl": {
                    "type": "string",
                    "example": "https://wg-agent-nyc.example.com"
                },
                "bandwidthLimitMbps": {
                    "type": "integer",
                    "example": 1000
                },
                "countryCode": {
                    "type": "string",
                    "example": "US"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-02-07T10:30:00Z"
                },
                "currentClients": {
                    "type": "integer",
                    "example": 42
                },
                "healthStatus": {
                    "type": "string",
                    "example": "healthy"
                },
                "id": {
                    "type": "string",
                    "example": "us-newyork"
                },
                "latitude": {
                    "type": "number",
                    "example": 40.7128
                },
                "location": {
                    "type": "string",
                    "example": "New York, USA"
                },
                "longitude": {
                    "type": "number",
                    "example": -74.006
                },
                "maxClients": {
                    "type": "integer",
                    "example": 250
                },
                "name": {
                    "type": "string",
                    "example": "New York"
                },
                "networkCidr": {
                    "type": "string",
                    "example": "192.168.88.0/24"
                },
                "publicIp": {
                    "type": "string",
                    "example": "192.0.2.1"
                },
                "regionCode": {
                    "type": "string",
                    "example": "us-east"
                },
                "serverPublicKey": {
                    "type": "string",
                    "example": "ABC123..."
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-02-07T10:35:00Z"
                },
                "wireguardPort": {
                    "type": "integer",
                    "example": 51820
                }
            }
        },
        "dto.ToggleRequest": {
            "type": "object",
            "required": [
                "action",
                "publicKey"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "connect",
                        "disconnect"
                    ],
                    "example": "connect"
                },
                "publicKey": {
                    "type": "string",
                    "example": "QGF4I+0L7klYTozF8pFDZUKC4fGt3tEuCakfWYghN0Y="
                }
            }
        },
        "dto.ToggleResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "connect"
                },
                "lastConnected": {
                    "type": "string",
                    "example": "2025-02-07T08:35:00Z"
                },
                "publicKey": {
                    "type": "string",
                    "example": "QGF4I+0L7klYTozF8pFDZUKC4fGt3tEuCakfWYghN0Y="
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-02-07T08:35:00Z"
                },
                "userId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.UpdateServerStatusRequest": {
            "type": "object",
            "required": [
                "healthStatus",
                "status"
            ],
            "properties": {
                "healthStatus": {
                    "type": "string",
                    "enum": [
                        "healthy",
                        "degraded",
                        "down",
                        "unknown"
                    ],
                    "example": "healthy"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "maintenance",
                        "offline",
                        "full"
                    ],
                    "example": "active"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "email",
                "id",
                "ip",
                "privateKey",
                "publicKey"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "lastConnected": {
                    "type": "string"
                },
                "privateKey": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                },
                "serverId": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "disconnected"
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "response.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.JSONResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/response.ErrorDetail"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "VPN Management API",
	Description:      "Production-ready WireGuard VPN management microservice with comprehensive API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
